from typing import Callable, List, Optional, Sequence, Tuple

NativeToolSpec = Tuple[str, str, str, bool, bool, Callable[..., object]]

class EventStream:
    def next_event(self) -> Optional[str]: ...
    def cancel(self) -> None: ...

class NativeAgent:
    def __init__(self, config_json: str, tools: Sequence[NativeToolSpec]) -> None: ...
    def warnings(self) -> List[str]: ...
    def describe(self) -> str: ...
    def ask_events(self, ask_json: str) -> EventStream: ...
    def feedback(self, trace_id: str, payload_json: str) -> str: ...
    def feedback_for(self, trace_id: str) -> str: ...
    def traces(self) -> str: ...
    def stats(self, options_json: str) -> str: ...
