//! The `Ask`/`Answer` contract — the one-way door of the subagent layer.
//!
//! Plain data: every struct here is `pub` fields with stable snake_case wire
//! names; non-required fields `#[serde(default)]` so minimal JSON loads. The
//! committed JSON schemas (`schemas/ask.schema.json`,
//! `schemas/answer.schema.json`) are pinned by `tests/contract.rs`.

use serde::{Deserialize, Deserializer, Serialize};
use serde_json::{Value, json};

/// Opaque identifier of one immutable stored trace.
///
/// Generated by the trace store; carried on [`Ask`] to resume/fork and
/// returned on every [`Answer`]. The wire form is a plain JSON string.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize)]
#[serde(transparent)]
pub struct TraceId(String);

impl TraceId {
    /// Wrap an identifier produced by a trace store.
    pub fn new(id: impl Into<String>) -> Self {
        Self::try_new(id).expect("trace ids produced by the host are valid")
    }

    /// Validate an identifier received at a host boundary.
    pub fn try_new(id: impl Into<String>) -> Result<Self, String> {
        let id = id.into();
        if !id.is_empty()
            && id
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        {
            Ok(Self(id))
        } else {
            Err("trace id must contain only ASCII letters, digits, '-' or '_'".to_string())
        }
    }

    /// The identifier as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl<'de> Deserialize<'de> for TraceId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let id = String::deserialize(deserializer)?;
        Self::try_new(id).map_err(serde::de::Error::custom)
    }
}

impl std::fmt::Display for TraceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl From<TraceId> for String {
    fn from(id: TraceId) -> String {
        id.0
    }
}

/// How a blob's bytes are referenced: inline, by path on the local filesystem,
/// or content-addressed into the blob store.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum BlobRef {
    /// Inline bytes, base64-encoded on the wire.
    Bytes { base64: String },
    /// A path readable by the receiving host (orchestrator-local hand-in).
    Path { path: String },
    /// A content-addressed ref into the `hugr-replay` blob store (sha-256 hex).
    Sha256 { sha256: String },
}

/// A file handed into or out of an ask — a typed contract slot, not `extra`,
/// because orchestrator↔agent file flow is part of the contract.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlobHandle {
    /// Where the bytes are.
    #[serde(rename = "ref")]
    pub blob_ref: BlobRef,
    /// IANA media type of the payload (e.g. `application/pdf`).
    pub media_type: String,
    /// Suggested file name inside the scratchpad; the host may sanitize it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// One question to a subagent. `question` is the only required field;
/// everything else defaults.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Ask {
    /// The question text.
    pub question: String,
    /// Resume/fork anchor: run this ask as a follow-up of the identified
    /// stored trace. `None` starts a fresh root trace.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<TraceId>,
    /// Inbound files, materialized into the scratchpad before the turn.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blobs: Vec<BlobHandle>,
    /// Skill folders supplied for this invocation. Each folder contains a
    /// standard `SKILL.md`; the host discovers them and exposes their content
    /// to the model through progressive disclosure.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub skills: Vec<String>,
    /// Opaque caller metadata, echoed into the trace. Never interpreted.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub extra: Value,
}

impl Ask {
    /// An ask with only the required question; everything else defaulted.
    pub fn new(question: impl Into<String>) -> Self {
        Self {
            question: question.into(),
            ..Self::default()
        }
    }
}

/// `Answer.status` when the agent answered the question. The only other
/// produced value is [`STATUS_ERROR`] — an open string set, not an enum,
/// because nothing here branches beyond success-vs-not.
pub const STATUS_SUCCESS: &str = "success";
/// `Answer.status` when the run failed (limits, transport, no final answer,
/// …); `response.error` carries the human-readable reason. Errors are answers —
/// still a full [`Answer`], exit code 0 on a CLI.
pub const STATUS_ERROR: &str = "error";

/// Mandatory accounting on every [`Answer`]. Derivable from the persisted trace
/// alone — `OpMeta` usage × per-tier pricing — including sub-agent children.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct AnswerMeta {
    /// Wall-clock duration of the ask, in milliseconds.
    pub duration_ms: u64,
    /// Total cost in micro-USD (1 USD = 1_000_000).
    pub cost_micro_usd: u64,
    /// Total prompt tokens across all model calls (children included).
    pub tokens_in: u64,
    /// Total completion tokens across all model calls (children included).
    pub tokens_out: u64,
    /// Number of model calls made.
    pub model_calls: u32,
    /// Number of tool invocations made.
    pub tool_calls: u32,
}

impl AnswerMeta {
    /// Fold a delegated child agent's accounting into this meta: the child's
    /// tokens/cost/calls roll up so the caller's cost line stays complete.
    /// Duration is *not* added — the parent's wall-clock already spans the
    /// child's synchronous call.
    pub fn merge_child(&mut self, child: &AnswerMeta) {
        self.cost_micro_usd += child.cost_micro_usd;
        self.tokens_in += child.tokens_in;
        self.tokens_out += child.tokens_out;
        self.model_calls += child.model_calls;
        self.tool_calls += child.tool_calls;
    }
}

/// The uniform result of one ask.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Answer {
    /// Outcome to branch on: [`STATUS_SUCCESS`] or [`STATUS_ERROR`].
    pub status: String,
    /// Structured response object. Hugr only requires this to be a JSON object;
    /// a typed response contract may cast it into a narrower Rust type.
    pub response: Value,
    /// The **new** trace this run persisted — the anchor for follow-ups and
    /// forks.
    pub trace_id: TraceId,
    /// Outbound files, content-addressed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blobs: Vec<BlobHandle>,
    /// Mandatory accounting.
    pub metadata: AnswerMeta,
    /// Agent-specific structured extras; never load-bearing for the contract.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub extra: Value,
}

impl Default for Answer {
    fn default() -> Self {
        Self {
            status: String::new(),
            response: json!({}),
            trace_id: TraceId::default(),
            blobs: Vec::new(),
            metadata: AnswerMeta::default(),
            extra: Value::Null,
        }
    }
}
