//! The `Ask`/`Answer` contract — the one-way door of the subagent layer
//! (ARCHITECTURE §18.1, ROADMAP T0.1).
//!
//! Plain data: every struct here is `pub` fields with stable snake_case wire
//! names; non-required fields `#[serde(default)]` so minimal JSON loads. The
//! committed JSON schemas (`schemas/ask.schema.json`,
//! `schemas/answer.schema.json`) are pinned by `tests/contract.rs`.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Opaque identifier of one immutable stored trace (ARCHITECTURE §19.1).
///
/// Generated by the trace store; carried on [`Ask`] to resume/fork and
/// returned on every [`Answer`]. The wire form is a plain JSON string.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TraceId(String);

impl TraceId {
    /// Wrap an identifier produced by a trace store.
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// The identifier as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for TraceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl From<TraceId> for String {
    fn from(id: TraceId) -> String {
        id.0
    }
}

/// How a blob's bytes are referenced (ARCHITECTURE §18.3): inline, by path on
/// the local filesystem, or content-addressed into the blob store.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum BlobRef {
    /// Inline bytes, base64-encoded on the wire.
    Bytes { base64: String },
    /// A path readable by the receiving host (orchestrator-local hand-in).
    Path { path: String },
    /// A content-addressed ref into the `hugr-replay` blob store (sha-256 hex).
    Sha256 { sha256: String },
}

/// A file handed into or out of an ask — a typed contract slot, not `extra`,
/// because orchestrator↔agent file flow is part of the contract (§18.3).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlobHandle {
    /// Where the bytes are.
    #[serde(rename = "ref")]
    pub blob_ref: BlobRef,
    /// IANA media type of the payload (e.g. `application/pdf`).
    pub media_type: String,
    /// Suggested file name inside the scratchpad; the host may sanitize it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// One question to a subagent (ARCHITECTURE §18.1). `question` is the only
/// required field; everything else defaults.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Ask {
    /// The question text.
    pub question: String,
    /// Resume/fork anchor: run this ask as a follow-up of the identified
    /// stored trace (§19.2). `None` starts a fresh root trace.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<TraceId>,
    /// Inbound files, materialized into the scratchpad before the turn (§18.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blobs: Vec<BlobHandle>,
    /// Opaque caller metadata, echoed into the trace. Never interpreted.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub extra: Value,
}

impl Ask {
    /// An ask with only the required question; everything else defaulted.
    pub fn new(question: impl Into<String>) -> Self {
        Self {
            question: question.into(),
            ..Self::default()
        }
    }
}

/// `Answer.status` when the agent answered the question. The only other
/// produced value is [`STATUS_ERROR`] — an open string set, not an enum,
/// because nothing here branches beyond success-vs-not (§14).
pub const STATUS_SUCCESS: &str = "success";
/// `Answer.status` when the run failed (limits, transport, no final answer,
/// …); `message` carries the human-readable reason. Errors are answers —
/// still a full [`Answer`], exit code 0 on a CLI.
pub const STATUS_ERROR: &str = "error";

/// Per-tier spend line inside [`AnswerMeta`] (ARCHITECTURE §18.4).
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TierSpend {
    /// The tier selector this line aggregates (`small` / `medium` / `big`).
    pub selector: String,
    /// Model calls made on this tier.
    pub model_calls: u32,
    /// Prompt tokens consumed on this tier.
    pub tokens_in: u64,
    /// Completion tokens produced on this tier.
    pub tokens_out: u64,
    /// Cost of this tier's usage, in micro-USD.
    pub cost_micro_usd: u64,
}

/// Mandatory accounting on every [`Answer`] (ARCHITECTURE §18.4). Derivable
/// from the persisted trace alone — `OpMeta` usage × per-tier pricing —
/// including sub-agent children.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct AnswerMeta {
    /// Wall-clock duration of the ask, in milliseconds.
    pub duration_ms: u64,
    /// Total cost in micro-USD (1 USD = 1_000_000).
    pub cost_micro_usd: u64,
    /// Total prompt tokens across all model calls (children included).
    pub tokens_in: u64,
    /// Total completion tokens across all model calls (children included).
    pub tokens_out: u64,
    /// Number of model calls made.
    pub model_calls: u32,
    /// Number of tool invocations made.
    pub tool_calls: u32,
    /// Per-tier breakdown; sums to the totals above.
    #[serde(default)]
    pub per_tier: Vec<TierSpend>,
}

impl AnswerMeta {
    /// Append one tier's spend line and fold it into the totals.
    pub fn add_tier(&mut self, tier: TierSpend) {
        self.cost_micro_usd += tier.cost_micro_usd;
        self.tokens_in += tier.tokens_in;
        self.tokens_out += tier.tokens_out;
        self.model_calls += tier.model_calls;
        self.per_tier.push(tier);
    }

    /// Fold a delegated child agent's accounting into this meta (ARCHITECTURE
    /// §18.4/§20.5): the child's tokens/cost/calls roll up so the caller's cost
    /// line stays complete. Per-tier lines merge by selector (child tiers are
    /// added to a matching parent line, else appended). Duration is *not* added
    /// — the parent's wall-clock already spans the child's synchronous call.
    pub fn merge_child(&mut self, child: &AnswerMeta) {
        self.cost_micro_usd += child.cost_micro_usd;
        self.tokens_in += child.tokens_in;
        self.tokens_out += child.tokens_out;
        self.model_calls += child.model_calls;
        self.tool_calls += child.tool_calls;
        for tier in &child.per_tier {
            if let Some(existing) = self
                .per_tier
                .iter_mut()
                .find(|t| t.selector == tier.selector)
            {
                existing.model_calls += tier.model_calls;
                existing.tokens_in += tier.tokens_in;
                existing.tokens_out += tier.tokens_out;
                existing.cost_micro_usd += tier.cost_micro_usd;
            } else {
                self.per_tier.push(tier.clone());
            }
        }
    }
}

/// The uniform result of one ask (ARCHITECTURE §18.1).
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Answer {
    /// Outcome to branch on: [`STATUS_SUCCESS`] or [`STATUS_ERROR`].
    pub status: String,
    /// The answer text (or the error text when `status` is `"error"`).
    pub message: String,
    /// The **new** trace this run persisted (§19.2) — the anchor for
    /// follow-ups and forks.
    pub trace_id: TraceId,
    /// Outbound files, content-addressed (§18.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blobs: Vec<BlobHandle>,
    /// Mandatory accounting.
    pub metadata: AnswerMeta,
    /// Agent-specific structured extras; never load-bearing for the contract.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub extra: Value,
}
