//! The `Ask`/`Answer` contract — the one-way door of the subagent layer
//! (ARCHITECTURE §18.1, ROADMAP T0.1).
//!
//! Wire stability: every struct/enum here is `#[non_exhaustive]`, serializes
//! with stable snake_case field names, and deserializes with `#[serde(default)]`
//! on every non-required field so older JSON keeps loading as the contract
//! grows. The committed JSON schemas (`schemas/ask.schema.json`,
//! `schemas/answer.schema.json`) are pinned by `tests/contract.rs`.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Opaque identifier of one immutable stored trace (ARCHITECTURE §19.1).
///
/// Generated by the trace store; carried on [`Ask`] to resume/fork and
/// returned on every [`Answer`]. The wire form is a plain JSON string.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TraceId(String);

impl TraceId {
    /// Wrap an identifier produced by a trace store.
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// The identifier as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for TraceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl From<TraceId> for String {
    fn from(id: TraceId) -> String {
        id.0
    }
}

/// Permission bits applied when a blob is materialized into the scratchpad
/// (ARCHITECTURE §18.3). Enforcement v1 is materialize-with-mode-bits inside
/// the jail; anything stronger is a host upgrade behind the same type.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct BlobPerms {
    pub read: bool,
    #[serde(default)]
    pub write: bool,
    #[serde(default)]
    pub execute: bool,
}

impl BlobPerms {
    /// Explicit permission bits.
    pub fn new(read: bool, write: bool, execute: bool) -> Self {
        Self {
            read,
            write,
            execute,
        }
    }

    /// The default for inbound material: readable, nothing else.
    pub fn read_only() -> Self {
        Self::new(true, false, false)
    }
}

impl Default for BlobPerms {
    fn default() -> Self {
        Self::read_only()
    }
}

/// How a blob's bytes are referenced (ARCHITECTURE §18.3): inline, by path on
/// the local filesystem, or content-addressed into the blob store.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[non_exhaustive]
pub enum BlobRef {
    /// Inline bytes, base64-encoded on the wire.
    Bytes { base64: String },
    /// A path readable by the receiving host (orchestrator-local hand-in).
    Path { path: String },
    /// A content-addressed ref into the `hugr-replay` blob store (sha-256 hex).
    Sha256 { sha256: String },
}

/// A file handed into or out of an ask — a typed contract slot, not `extra`,
/// because orchestrator↔agent file flow is part of the contract (§18.3).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct BlobHandle {
    /// Where the bytes are.
    #[serde(rename = "ref")]
    pub blob_ref: BlobRef,
    /// IANA media type of the payload (e.g. `application/pdf`).
    pub media_type: String,
    /// Mode bits applied on materialization.
    #[serde(default)]
    pub perms: BlobPerms,
    /// Suggested file name inside the scratchpad; the host may sanitize it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl BlobHandle {
    /// A handle with default (read-only) perms and no name hint.
    pub fn new(blob_ref: BlobRef, media_type: impl Into<String>) -> Self {
        Self {
            blob_ref,
            media_type: media_type.into(),
            perms: BlobPerms::default(),
            name: None,
        }
    }

    /// Override the materialization permission bits.
    pub fn with_perms(mut self, perms: BlobPerms) -> Self {
        self.perms = perms;
        self
    }

    /// Suggest a file name for materialization inside the scratchpad.
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }
}

/// A resource an orchestrator hands to a subagent as part of a
/// [`ResourceGroup`] (ARCHITECTURE §18.5). A tool whose manifest scope binds
/// `group:<name>` is registered against these once a matching [`ResourceGrant`]
/// arrives. `#[non_exhaustive]` — new resource kinds don't break the contract.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[non_exhaustive]
pub enum ResourceRef {
    /// A directory subtree (becomes an `fs_read`/`fs_write` jail root).
    FsRoot { path: String },
    /// A content-addressed payload (§18.3).
    Blob { handle: BlobHandle },
    /// A SQLite database file.
    Sqlite { path: String },
    /// A network origin (an `http_fetch` allowlist host).
    HttpHost { host: String },
}

/// A named bundle of resources the orchestrator owns and may hand to a
/// subagent (ARCHITECTURE §18.5). Rides the [`Ask`]; a manifest tool scope
/// binds a group by name (`root = "group:policies"`).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ResourceGroup {
    pub name: String,
    #[serde(default)]
    pub resources: Vec<ResourceRef>,
}

impl ResourceGroup {
    pub fn new(name: impl Into<String>, resources: Vec<ResourceRef>) -> Self {
        Self {
            name: name.into(),
            resources,
        }
    }
}

/// The access level an orchestrator grants on a [`ResourceGroup`]. Absence of a
/// grant means *no access* — the bound tool is simply never registered.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum Access {
    /// Read-class tools only (`fs_read`, read-only `sqlite_query`).
    Read,
    /// Read-class tools plus mutating tools bound to the group.
    ReadWrite,
}

impl Access {
    /// Whether this granted access satisfies a tool requiring `required`
    /// (`ReadWrite` satisfies both; `Read` satisfies only `Read`).
    pub fn satisfies(self, required: Access) -> bool {
        matches!(
            (self, required),
            (Access::ReadWrite, _) | (Access::Read, Access::Read)
        )
    }
}

/// One grant: the access level the orchestrator confers on a named group
/// (ARCHITECTURE §18.5). Grants ride the [`Ask`] and are recorded in the trace.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ResourceGrant {
    pub group: String,
    pub access: Access,
}

impl ResourceGrant {
    pub fn new(group: impl Into<String>, access: Access) -> Self {
        Self {
            group: group.into(),
            access,
        }
    }
}

/// One question to a subagent (ARCHITECTURE §18.1). `question` is the only
/// required field; everything else defaults.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Ask {
    /// The question text.
    pub question: String,
    /// Resume/fork anchor: run this ask as a follow-up of the identified
    /// stored trace (§19.2). `None` starts a fresh root trace.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<TraceId>,
    /// Inbound files, materialized into the scratchpad before the turn (§18.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blobs: Vec<BlobHandle>,
    /// Orchestrator-supplied resource groups this ask offers (§18.5). A tool
    /// bound to `group:<name>` resolves its scope from the matching group.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub groups: Vec<ResourceGroup>,
    /// Access grants over the offered groups (§18.5). No grant ⇒ no access ⇒
    /// the bound tool is never registered for this ask.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub grants: Vec<ResourceGrant>,
    /// Opaque caller metadata, echoed into the trace. Never interpreted.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub extra: Value,
}

impl Ask {
    /// An ask with only the required question; everything else defaulted.
    pub fn new(question: impl Into<String>) -> Self {
        Self {
            question: question.into(),
            trace_id: None,
            blobs: Vec::new(),
            groups: Vec::new(),
            grants: Vec::new(),
            extra: Value::Null,
        }
    }

    /// Anchor this ask on a stored trace (resume; ask twice from the same
    /// parent to fork).
    pub fn with_trace_id(mut self, trace_id: TraceId) -> Self {
        self.trace_id = Some(trace_id);
        self
    }

    /// Hand files in.
    pub fn with_blobs(mut self, blobs: Vec<BlobHandle>) -> Self {
        self.blobs = blobs;
        self
    }

    /// Offer resource groups (§18.5).
    pub fn with_groups(mut self, groups: Vec<ResourceGroup>) -> Self {
        self.groups = groups;
        self
    }

    /// Grant access over offered groups (§18.5).
    pub fn with_grants(mut self, grants: Vec<ResourceGrant>) -> Self {
        self.grants = grants;
        self
    }

    /// Attach opaque caller metadata.
    pub fn with_extra(mut self, extra: Value) -> Self {
        self.extra = extra;
        self
    }
}

/// The tri-state outcome every surface branches on. Errors are answers —
/// `Error` still returns a full [`Answer`] (and exit code 0 on a CLI).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum AnswerStatus {
    /// The agent answered the question.
    Success,
    /// The question is outside this agent's declared domain.
    OffTopic,
    /// The run failed (limits, transport, no final answer, …); `message`
    /// carries the human-readable reason.
    Error,
}

/// Per-tier spend line inside [`AnswerMeta`] (ARCHITECTURE §18.4).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TierSpend {
    /// The tier selector this line aggregates (`small` / `medium` / `big`).
    pub selector: String,
    /// Model calls made on this tier.
    pub model_calls: u32,
    /// Prompt tokens consumed on this tier.
    pub tokens_in: u64,
    /// Completion tokens produced on this tier.
    pub tokens_out: u64,
    /// Cost of this tier's usage, in micro-USD.
    pub cost_micro_usd: u64,
}

impl TierSpend {
    /// One aggregated spend line for a tier.
    pub fn new(
        selector: impl Into<String>,
        model_calls: u32,
        tokens_in: u64,
        tokens_out: u64,
        cost_micro_usd: u64,
    ) -> Self {
        Self {
            selector: selector.into(),
            model_calls,
            tokens_in,
            tokens_out,
            cost_micro_usd,
        }
    }
}

/// Mandatory accounting on every [`Answer`] (ARCHITECTURE §18.4). Derivable
/// from the persisted trace alone — `OpMeta` usage × per-tier pricing —
/// including sub-agent children.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AnswerMeta {
    /// Wall-clock duration of the ask, in milliseconds.
    pub duration_ms: u64,
    /// Total cost in micro-USD (1 USD = 1_000_000).
    pub cost_micro_usd: u64,
    /// Total prompt tokens across all model calls (children included).
    pub tokens_in: u64,
    /// Total completion tokens across all model calls (children included).
    pub tokens_out: u64,
    /// Number of model calls made.
    pub model_calls: u32,
    /// Number of tool invocations made.
    pub tool_calls: u32,
    /// Per-tier breakdown; sums to the totals above.
    #[serde(default)]
    pub per_tier: Vec<TierSpend>,
}

impl AnswerMeta {
    /// Zeroed accounting (an error before any model call still carries meta).
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the wall-clock duration.
    pub fn with_duration_ms(mut self, duration_ms: u64) -> Self {
        self.duration_ms = duration_ms;
        self
    }

    /// Set the tool-call count.
    pub fn with_tool_calls(mut self, tool_calls: u32) -> Self {
        self.tool_calls = tool_calls;
        self
    }

    /// Append one tier's spend line and fold it into the totals.
    pub fn with_tier(mut self, tier: TierSpend) -> Self {
        self.cost_micro_usd += tier.cost_micro_usd;
        self.tokens_in += tier.tokens_in;
        self.tokens_out += tier.tokens_out;
        self.model_calls += tier.model_calls;
        self.per_tier.push(tier);
        self
    }

    /// Fold a delegated child agent's accounting into this meta (ARCHITECTURE
    /// §18.4/§20.5): the child's tokens/cost/calls roll up so the caller's cost
    /// line stays complete. Per-tier lines merge by selector (child tiers are
    /// added to a matching parent line, else appended). Duration is *not* added
    /// — the parent's wall-clock already spans the child's synchronous call.
    pub fn merge_child(&mut self, child: &AnswerMeta) {
        self.cost_micro_usd += child.cost_micro_usd;
        self.tokens_in += child.tokens_in;
        self.tokens_out += child.tokens_out;
        self.model_calls += child.model_calls;
        self.tool_calls += child.tool_calls;
        for tier in &child.per_tier {
            if let Some(existing) = self.per_tier.iter_mut().find(|t| t.selector == tier.selector) {
                existing.model_calls += tier.model_calls;
                existing.tokens_in += tier.tokens_in;
                existing.tokens_out += tier.tokens_out;
                existing.cost_micro_usd += tier.cost_micro_usd;
            } else {
                self.per_tier.push(tier.clone());
            }
        }
    }
}

/// The uniform result of one ask (ARCHITECTURE §18.1).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Answer {
    /// Outcome to branch on.
    pub status: AnswerStatus,
    /// The answer text (or the error text when `status` is `Error`).
    pub message: String,
    /// The **new** trace this run persisted (§19.2) — the anchor for
    /// follow-ups and forks.
    pub trace_id: TraceId,
    /// Outbound files, content-addressed (§18.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blobs: Vec<BlobHandle>,
    /// Mandatory accounting.
    pub metadata: AnswerMeta,
    /// Agent-specific structured extras (schema-declarable, ROADMAP T3.4);
    /// never load-bearing for the contract.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub extra: Value,
    /// Advisory, non-fatal notices about this answer — e.g. `extra` failing its
    /// manifest-declared schema (ROADMAP T3.4). Never load-bearing; empty by
    /// default, so the wire form is unchanged for callers that emit no warnings.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub warnings: Vec<String>,
}

impl Answer {
    /// An answer with the required fields; blobs/extra default empty.
    pub fn new(
        status: AnswerStatus,
        message: impl Into<String>,
        trace_id: TraceId,
        metadata: AnswerMeta,
    ) -> Self {
        Self {
            status,
            message: message.into(),
            trace_id,
            blobs: Vec::new(),
            metadata,
            extra: Value::Null,
            warnings: Vec::new(),
        }
    }

    /// Attach outbound files.
    pub fn with_blobs(mut self, blobs: Vec<BlobHandle>) -> Self {
        self.blobs = blobs;
        self
    }

    /// Attach agent-specific structured extras.
    pub fn with_extra(mut self, extra: Value) -> Self {
        self.extra = extra;
        self
    }

    /// Attach advisory, non-fatal warnings.
    pub fn with_warnings(mut self, warnings: Vec<String>) -> Self {
        self.warnings = warnings;
        self
    }
}
