//! The trace store — immutable traces with `trace_id` / `depends_on` lineage
//! (ARCHITECTURE §19.1, ROADMAP T0.2).
//!
//! A [`TraceStore`] is a directory of **immutable** [`Trace`] files, each keyed
//! by a generated [`TraceId`] and carrying header metadata (agent name/version,
//! the question, the outcome status, and the `depends_on` lineage pointer) in
//! its [`TraceMeta`]. The store is the orchestration-facing wrapper around the
//! existing replay machinery: it names and files what `hugr-replay` already
//! persists, adding nothing to the core.
//!
//! ## Immutability & lineage
//!
//! Traces are write-once: [`TraceStore::put`] refuses to overwrite an existing
//! id, and a resumed ask persists a **new** trace whose `depends_on` names the
//! parent (§19.2) — the parent is never mutated. Lineage is therefore a DAG
//! recorded entirely in headers; forking is just asking the same parent twice.
//!
//! ## Determinism of `trace_id`
//!
//! The store is host-side, so IO is fine — but the repo's determinism story
//! still applies: ids come from **content**, not from RNG or a clock. The id is
//! the SHA-256 of the trace's serialized JSON (as handed to `put`, before the
//! id itself is stamped in), truncated to 16 hex chars, with a monotonic
//! collision-checked `-N` suffix appended if that id is already taken. The same
//! trace bytes always propose the same id; distinct traces landing on the same
//! prefix get distinct suffixes deterministically (first free counter).
//!
//! ## IO shape
//!
//! Writes are atomic (temp file + rename, via [`Trace::save_atomic`]), so a
//! crash can never leave a half-written trace at a keyed path. [`head`] parses
//! only the `meta` header out of the file — no event vector is materialized,
//! nothing is folded — so listing lineage stays cheap; [`get`]
//! loads the full trace with zero IO beyond the one file read.
//!
//! [`head`]: TraceStore::head
//! [`get`]: TraceStore::get

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use hugr_replay::{Trace, TraceError, TraceMeta};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::contract::TraceId;

/// The header of one stored trace (ARCHITECTURE §19.1): everything a lineage
/// listing needs, readable without folding events. A projection of the stored
/// trace's [`TraceMeta`] with the store-required fields made non-optional.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[non_exhaustive]
pub struct TraceHead {
    /// The store key of this trace.
    pub trace_id: TraceId,
    /// The parent this trace resumed from; `None` for a root trace (§19.2).
    pub depends_on: Option<TraceId>,
    /// Name of the agent that recorded the trace.
    pub agent_name: String,
    /// Version of the agent that recorded the trace.
    pub agent_version: String,
    /// Host-defined logical creation timestamp (the session's `seq 0` tick).
    pub created_at: Option<u64>,
    /// The question this ask answered.
    pub question: String,
    /// The ask's outcome status wire string (`"success"` / `"off_topic"` /
    /// `"error"`); opaque here — the store never branches on it.
    pub status: String,
}

impl TraceHead {
    /// Construct a head (external tooling/surfaces need this since the struct is
    /// `#[non_exhaustive]`; the store produces heads via [`TraceStore::head`]).
    pub fn new(
        trace_id: TraceId,
        depends_on: Option<TraceId>,
        agent_name: impl Into<String>,
        agent_version: impl Into<String>,
        created_at: Option<u64>,
        question: impl Into<String>,
        status: impl Into<String>,
    ) -> Self {
        Self {
            trace_id,
            depends_on,
            agent_name: agent_name.into(),
            agent_version: agent_version.into(),
            created_at,
            question: question.into(),
            status: status.into(),
        }
    }
}

/// Store-supplied header fields stamped into a trace's [`TraceMeta`] on
/// [`TraceStore::put`]. The `trace_id` itself is generated by the store.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub struct TraceHeader {
    /// The parent trace this one resumed from; `None` for a root (§19.2).
    pub depends_on: Option<TraceId>,
    /// Name of the recording agent.
    pub agent_name: String,
    /// Version of the recording agent.
    pub agent_version: String,
    /// The question asked.
    pub question: String,
    /// The outcome status wire string; opaque to the store.
    pub status: String,
}

impl TraceHeader {
    /// A root-trace header (no `depends_on`).
    pub fn new(
        agent_name: impl Into<String>,
        agent_version: impl Into<String>,
        question: impl Into<String>,
        status: impl Into<String>,
    ) -> Self {
        Self {
            depends_on: None,
            agent_name: agent_name.into(),
            agent_version: agent_version.into(),
            question: question.into(),
            status: status.into(),
        }
    }

    /// Mark this trace as a follow-up of `parent` (resume/fork, §19.2).
    pub fn with_depends_on(mut self, parent: TraceId) -> Self {
        self.depends_on = Some(parent);
        self
    }
}

/// A directory-backed store of immutable traces keyed by [`TraceId`]
/// (ARCHITECTURE §19.1). See the module docs for the invariants.
#[derive(Clone, Debug)]
#[non_exhaustive]
pub struct TraceStore {
    root: PathBuf,
}

/// Deserialization target for [`TraceStore::head`]: only the `meta` header is
/// parsed out of the file; `events`, `commands`, `log`, `blobs`, and
/// `children` are skipped by serde, so no event vector is ever materialized.
#[derive(Deserialize)]
struct HeadOnly {
    meta: TraceMeta,
}

impl TraceStore {
    /// A store rooted at `root`. The directory is created lazily on the first
    /// [`put`](TraceStore::put); construction itself touches no IO.
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    /// The directory backing this store.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// The on-disk path a given id maps to.
    pub fn path_of(&self, id: &TraceId) -> PathBuf {
        self.root.join(format!("{id}.json"))
    }

    /// Persist `trace` as a **new** immutable trace: generate its id from the
    /// trace content (deterministic — no RNG, no clock), stamp `header` and
    /// the id into the trace's [`TraceMeta`], and write it atomically (temp
    /// file + rename). Returns the generated id.
    ///
    /// Existing ids are never overwritten — collisions get the first free
    /// `-N` suffix, so the store's immutability invariant holds even for a
    /// byte-identical re-put (which lands as a sibling entry).
    pub fn put(&self, mut trace: Trace, header: TraceHeader) -> Result<TraceId, StoreError> {
        std::fs::create_dir_all(&self.root)?;

        trace.meta.depends_on = header.depends_on.map(String::from);
        trace.meta.agent_name = Some(header.agent_name);
        trace.meta.agent_version = Some(header.agent_version);
        trace.meta.question = Some(header.question);
        trace.meta.status = Some(header.status);

        // Content-derived id: hash the headed trace *before* the id is stamped
        // in (the id cannot depend on itself), then collision-check against
        // the directory with a monotonic counter.
        let digest = Sha256::digest(trace.to_json()?);
        let base = format!("{digest:x}");
        let base = &base[..16];

        // Reserve the id's path **atomically** so concurrent asks are
        // collision-free (ROADMAP T3.2): two asks landing on the same content
        // hash must not both claim the same file. `create_new` is the atomic
        // claim — the loser sees `AlreadyExists` and bumps the `-N` suffix, so
        // parallel puts always produce distinct ids and no trace is ever
        // clobbered. (A bare `exists()` check would be a TOCTOU race.)
        let mut candidate = TraceId::new(base);
        let mut counter = 1u64;
        let reserved = loop {
            match std::fs::OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(self.path_of(&candidate))
            {
                Ok(file) => break file,
                Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => {
                    candidate = TraceId::new(format!("{base}-{counter}"));
                    counter += 1;
                }
                Err(err) => return Err(err.into()),
            }
        };
        drop(reserved);

        trace.meta.trace_id = Some(candidate.as_str().to_string());
        // The path is now reserved (an empty placeholder file); `save_atomic`
        // writes a uniquely-named temp file and renames over the placeholder,
        // so a reader never sees a half-written trace and the write stays
        // crash-atomic (ARCHITECTURE §15.1). The temp name derives from the
        // now-unique `candidate`, so concurrent puts never share a temp path.
        trace.save_atomic(self.path_of(&candidate))?;
        Ok(candidate)
    }

    /// Load the full trace stored under `id` — one file read, then a pure
    /// parse; re-folding it into a brain needs zero further IO.
    pub fn get(&self, id: &TraceId) -> Result<Trace, StoreError> {
        let path = self.path_of(id);
        if !path.exists() {
            return Err(StoreError::NotFound { id: id.clone() });
        }
        Ok(Trace::load(path)?)
    }

    /// Read the header of the trace stored under `id` **without** loading its
    /// events: only `meta` is deserialized (see [`HeadOnly`]).
    pub fn head(&self, id: &TraceId) -> Result<TraceHead, StoreError> {
        let path = self.path_of(id);
        if !path.exists() {
            return Err(StoreError::NotFound { id: id.clone() });
        }
        let bytes = std::fs::read(path)?;
        let head: HeadOnly = serde_json::from_slice(&bytes)?;
        Self::head_from_meta(id, head.meta)
    }

    /// List the headers of every stored trace, sorted by id (deterministic
    /// order regardless of directory-entry order). Lineage — `depends_on`
    /// pointers — is fully visible from this listing alone.
    pub fn list(&self) -> Result<Vec<TraceHead>, StoreError> {
        let mut heads = Vec::new();
        let entries = match std::fs::read_dir(&self.root) {
            Ok(entries) => entries,
            // An unused store lists as empty rather than erroring.
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(heads),
            Err(err) => return Err(err.into()),
        };
        for entry in entries {
            let path = entry?.path();
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            heads.push(self.head(&TraceId::new(stem))?);
        }
        heads.sort_by(|a, b| a.trace_id.cmp(&b.trace_id));
        Ok(heads)
    }

    /// Report the store's on-disk size: how many traces it holds and their
    /// total bytes (ROADMAP T3.3). Only the `.json` trace files are counted —
    /// the sibling `.scratch`/`.blobs` subtrees are separate concerns.
    pub fn size(&self) -> Result<StoreSize, StoreError> {
        let heads = self.list()?;
        let mut total_bytes = 0u64;
        for head in &heads {
            total_bytes += std::fs::metadata(self.path_of(&head.trace_id))?.len();
        }
        Ok(StoreSize {
            trace_count: heads.len(),
            total_bytes,
        })
    }

    /// Prune traces under a retention `policy`, **keeping every survivor's
    /// lineage closed** (ROADMAP T3.3): a trace is deleted only if it is a
    /// policy drop-candidate *and* no surviving trace depends on it
    /// (transitively). So a survivor's `depends_on` chain up to its root always
    /// still resolves — pruning can never orphan a kept trace.
    ///
    /// Policy (all optional; a trace is a drop-candidate if it fails **any**
    /// active bound and is not pinned): `keep_max` keeps the N most-recently
    /// modified traces; `max_age_secs` drops traces older than that (by file
    /// mtime); `pinned` ids (typically pinned roots) are never dropped. Age/LRU
    /// use filesystem mtime — this is host maintenance, outside the deterministic
    /// replay path. Returns which ids were pruned/kept and the bytes freed.
    pub fn prune(&self, policy: &PrunePolicy) -> Result<PruneReport, StoreError> {
        let heads = self.list()?;
        let ids: BTreeSet<TraceId> = heads.iter().map(|h| h.trace_id.clone()).collect();
        let parent: BTreeMap<TraceId, Option<TraceId>> = heads
            .iter()
            .map(|h| (h.trace_id.clone(), h.depends_on.clone()))
            .collect();

        let mut mtimes: BTreeMap<TraceId, SystemTime> = BTreeMap::new();
        for head in &heads {
            let mtime = std::fs::metadata(self.path_of(&head.trace_id))?.modified()?;
            mtimes.insert(head.trace_id.clone(), mtime);
        }

        // The `keep_max` newest by mtime (tie-broken by id for determinism).
        let within_count: BTreeSet<TraceId> = match policy.keep_max {
            Some(n) => {
                let mut ranked: Vec<&TraceHead> = heads.iter().collect();
                ranked.sort_by(|a, b| {
                    mtimes[&b.trace_id]
                        .cmp(&mtimes[&a.trace_id])
                        .then_with(|| a.trace_id.cmp(&b.trace_id))
                });
                ranked
                    .into_iter()
                    .take(n)
                    .map(|h| h.trace_id.clone())
                    .collect()
            }
            None => ids.clone(),
        };

        let age_cutoff: Option<SystemTime> = policy
            .max_age_secs
            .and_then(|secs| SystemTime::now().checked_sub(Duration::from_secs(secs)));

        // Initial keep set: everything not dropped by policy.
        let mut keep: BTreeSet<TraceId> = BTreeSet::new();
        for head in &heads {
            let id = &head.trace_id;
            if policy.pinned.contains(id) {
                keep.insert(id.clone());
                continue;
            }
            let too_old = age_cutoff.is_some_and(|cutoff| mtimes[id] < cutoff);
            let beyond_count = policy.keep_max.is_some() && !within_count.contains(id);
            if !(too_old || beyond_count) {
                keep.insert(id.clone());
            }
        }

        // Lineage closure: pull every kept trace's ancestors back into the keep
        // set so no survivor is ever left with a dangling `depends_on`.
        let mut stack: Vec<TraceId> = keep.iter().cloned().collect();
        while let Some(id) = stack.pop() {
            if let Some(Some(dep)) = parent.get(&id) {
                if ids.contains(dep) && keep.insert(dep.clone()) {
                    stack.push(dep.clone());
                }
            }
        }

        // Delete the rest.
        let mut pruned = Vec::new();
        let mut freed_bytes = 0u64;
        for head in &heads {
            if keep.contains(&head.trace_id) {
                continue;
            }
            let path = self.path_of(&head.trace_id);
            freed_bytes += std::fs::metadata(&path)?.len();
            std::fs::remove_file(&path)?;
            pruned.push(head.trace_id.clone());
        }
        pruned.sort();
        let mut kept: Vec<TraceId> = keep.into_iter().collect();
        kept.sort();
        Ok(PruneReport {
            pruned,
            kept,
            freed_bytes,
        })
    }

    /// Project a stored [`TraceMeta`] into a [`TraceHead`], checking the
    /// store-required fields are present and the stamped id matches the key.
    fn head_from_meta(id: &TraceId, meta: TraceMeta) -> Result<TraceHead, StoreError> {
        let field_err = |field: &str| StoreError::CorruptHeader {
            id: id.clone(),
            reason: format!("missing header field `{field}`"),
        };
        let trace_id = meta.trace_id.ok_or_else(|| field_err("trace_id"))?;
        if trace_id != id.as_str() {
            return Err(StoreError::CorruptHeader {
                id: id.clone(),
                reason: format!("stamped trace_id `{trace_id}` does not match the file key"),
            });
        }
        Ok(TraceHead {
            trace_id: TraceId::new(trace_id),
            depends_on: meta.depends_on.map(TraceId::new),
            agent_name: meta.agent_name.ok_or_else(|| field_err("agent_name"))?,
            agent_version: meta
                .agent_version
                .ok_or_else(|| field_err("agent_version"))?,
            created_at: meta.created_at,
            question: meta.question.ok_or_else(|| field_err("question"))?,
            status: meta.status.ok_or_else(|| field_err("status"))?,
        })
    }
}

/// Retention policy for [`TraceStore::prune`] (ROADMAP T3.3). All bounds are
/// optional; the default policy keeps everything. Lineage closure is always
/// enforced regardless of policy — a survivor's ancestors are never dropped.
#[derive(Clone, Debug, Default)]
#[non_exhaustive]
pub struct PrunePolicy {
    /// Keep at most this many traces, the most-recently-modified ones.
    pub keep_max: Option<usize>,
    /// Drop traces whose file mtime is older than this many seconds.
    pub max_age_secs: Option<u64>,
    /// Ids that must never be dropped (typically pinned roots).
    pub pinned: BTreeSet<TraceId>,
}

impl PrunePolicy {
    pub fn new() -> Self {
        Self::default()
    }

    /// Keep at most `n` traces (the most-recently-modified survive).
    pub fn keep_max(mut self, n: usize) -> Self {
        self.keep_max = Some(n);
        self
    }

    /// Drop traces older than `secs` seconds (by file mtime).
    pub fn max_age_secs(mut self, secs: u64) -> Self {
        self.max_age_secs = Some(secs);
        self
    }

    /// Pin an id so it (and, by lineage closure, its ancestors) is never
    /// dropped.
    pub fn pin(mut self, id: TraceId) -> Self {
        self.pinned.insert(id);
        self
    }
}

/// Outcome of a [`TraceStore::prune`] pass.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[non_exhaustive]
pub struct PruneReport {
    /// Ids deleted (sorted).
    pub pruned: Vec<TraceId>,
    /// Ids retained (sorted) — includes ancestors kept for lineage closure.
    pub kept: Vec<TraceId>,
    /// Bytes freed by deleting the pruned trace files.
    pub freed_bytes: u64,
}

/// On-disk size report from [`TraceStore::size`].
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[non_exhaustive]
pub struct StoreSize {
    pub trace_count: usize,
    pub total_bytes: u64,
}

/// Errors from the trace store.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum StoreError {
    /// No trace is stored under the given id.
    #[error("trace not found in store: {id}")]
    NotFound { id: TraceId },

    /// A stored file is missing the store-required header fields or its
    /// stamped id disagrees with its file key (an externally tampered store —
    /// [`TraceStore::put`] always stamps a complete, matching header).
    #[error("corrupt trace header for {id}: {reason}")]
    CorruptHeader { id: TraceId, reason: String },

    /// The underlying trace format failed to read/write/parse.
    #[error(transparent)]
    Trace(#[from] TraceError),

    /// Filesystem access failed.
    #[error("trace store IO error: {0}")]
    Io(#[from] std::io::Error),

    /// The header of a stored file failed to parse as JSON.
    #[error("trace header parse error: {0}")]
    Serde(#[from] serde_json::Error),
}
